### ISSUE TITLE
Some multiline commands only run with the first line

### ISSUE THREAD

**Issue by capnspacehook** [gacts/run-and-post-run#14]
Here's a simple example of what triggers this behavior:

```yaml
- uses: gacts/run-and-post-run@v1
  with:
    run: |
      if [[ true == true ]]; then
        echo "true"
      else
        echo "false"
      fi
    post: |
      if [[ true == true ]]; then
        echo "true"
      else
        echo "false"
      fi
```

The output:

![image](https://github.com/gacts/run-and-post-run/assets/23243104/85aaef78-3da2-4781-94d2-9f4e64d19a51)

I suspect it's due to a bug in [`joinMultilineCommands`](https://github.com/gacts/run-and-post-run/blob/396569534aae5e9a3eda46fffc5bf93921dd3fe8/src/common.js#L26), but I know next to no Javascript/Typescript so I can't easily fix it myself.

Edit: after looking at the code a bit more closely, it seems the problem is because commands are always split into separate lines and run one line at a time. I think this makes sense when `shell` and/or `post-shell` is set to `""`  (invoking commands directly) and the user provided a list of commands. However is the shell is set, I think the input commands should not be modified and instead executed by the set shell as-is. Does that sound reasonable to you?

**Comment by tarampampam** [comment]
Could you try this?

```diff
4,7c4,7
<       if [[ true == true ]]; then
<         echo "true"
<       else
<         echo "false"
---
>       if [[ true == true ]]; then \
>         echo "true" \
>       else \
>         echo "false" \
10,13c10,13
<       if [[ true == true ]]; then
<         echo "true"
<       else
<         echo "false"
---
>       if [[ true == true ]]; then \
>         echo "true" \
>       else \
>         echo "false" \
```

**Comment by tarampampam** [comment]
Ping @capnspacehook

**Comment by tarampampam** [comment]
Closed due inactivity
