### ISSUE TITLE
Executing each line of the `run` and `post` parameters individually produces unexpected behavior

### ISSUE THREAD

**Issue by tcushman** [gacts/run-and-post-run#25]
I have been using this `run-and-post-run` action to develop some workflows.  It is very helpful, thank you for publishing this.  I have, however, encountered some unexpected behavior when attempting to set environment variables in a `run` or `post` script, and when attempting to use `if` / `else` statements.  Environment variables can be set, but are subsequently missing.  Multiline statements, like `if` / `else` / `fi`, that work in a regular `run` step produce "Unexpected end of file" errors.

After looking into the implementation a little, it looks like the cause of this unexpected behavior is each line of the scripts are being executed individually in the [runCommands() function](https://github.com/gacts/run-and-post-run/blob/5be80bb28e4f0f6441a05e13dd02ca42984f4eea/src/common.js#L61C27-L61C35).

**Comment by jetexe** [comment]
ping @tcushman

**Comment by jetexe** [comment]
Closed due to inactivity
